#!python
import sys
import subprocess
import scissors
import os
#get a path to the scissors module
path = os.path.dirname(scissors.__file__)
args = ["fab","-f",os.path.join(path,"fabfile")]
args += sys.argv[1:]
print args
subprocess.call(args)
